# Macro file for nDa
# To be run preferably in batch, without graphics:
# % nDa[a,b] runFe.mac

/tracking/storeTrajectory 0
/run/numberOfThreads 24
/run/initialize
/control/execute gps_iso.mac

/gps/particle neutron
/gps/energy 14 MeV
/analysis/setFileName 2HolesBoxOutput/14n-Fe3.root
/run/beamOn 1000000

/gps/energy 5 MeV
/analysis/setFileName 2HolesBoxOutput/5n-Fe3.root
/run/beamOn 1000000


#
#
#/gps/energy 14 MeV
#/nDa/det/setTargetRadius 1 cm
#/analysis/setFileName 2HolesBoxOutput/14n-Fe1.root
#/run/beamOn 1000000
#/nDa/det/setTargetRadius 2 cm
#/analysis/setFileName 2HolesBoxOutput/14n-Fe2.root
#/run/beamOn 1000000
#/nDa/det/setTargetRadius 3 cm
#/analysis/setFileName 2HolesBoxOutput/14n-Fe3.root
#/run/beamOn 1000000
#
#/gps/particle neutron
#/gps/energy 5 MeV
#/nDa/det/setTargetRadius 1 cm
#/analysis/setFileName 2HolesBoxOutput/5n-Fe1.root
#/run/beamOn 1000000
#/nDa/det/setTargetRadius 2 cm
#/analysis/setFileName 2HolesBoxOutput/5n-Fe2.root
#/run/beamOn 1000000
#/nDa/det/setTargetRadius 3 cm
#/analysis/setFileName 2HolesBoxOutput/5n-Fe3.root
#/run/beamOn 1000000