# Macro file for nDa
# 
# To be run preferably in batch, without graphics:
# % nDa[a,b] runFe.mac
#
/tracking/storeTrajectory 0
/run/numberOfThreads 24
/run/initialize
/control/execute gps_iso.mac
/gps/particle neutron

/gps/energy 5 MeV
/nDa/det/setTargetRadius 2 cm
/analysis/setFileName nDaMovingOutput/5n-x+1.root
/run/beamOn 1000000

/gps/energy 14 MeV
/nDa/det/setTargetRadius 2 cm
/analysis/setFileName nDaMovingOutput/14n-x+1.root
/run/beamOn 1000000