# Macro file for nDa
# 
# To be run preferably in batch, without graphics:
# % nDa[a,b] run.mac
#
/tracking/storeTrajectory 0
/run/numberOfThreads 24
/run/initialize
/control/execute gps_iso.mac
/gps/particle neutron
/gps/energy 5 MeV

/nDa/det/setTargetMaterial G4_Pb

/nDa/det/setTargetRadius 7 cm
/analysis/setFileName 5nLeadOutput/n-7cmPb.root
/run/beamOn 1000000

/nDa/det/setTargetRadius 6 cm
/analysis/setFileName 5nLeadOutput/n-6cmPb.root
/run/beamOn 1000000

/nDa/det/setTargetRadius 5 cm
/analysis/setFileName 5nLeadOutput/n-5cmPb.root
/run/beamOn 1000000

/nDa/det/setTargetRadius 4 cm
/analysis/setFileName 5nLeadOutput/n-4cmPb.root
/run/beamOn 1000000

/nDa/det/setTargetRadius 3 cm
/analysis/setFileName 5nLeadOutput/n-3cmPb.root
/run/beamOn 1000000

/nDa/det/setTargetRadius 2 cm
/analysis/setFileName 5nLeadOutput/n-2cmPb.root
/run/beamOn 1000000

/nDa/det/setTargetRadius 1 cm
/analysis/setFileName 5nLeadOutput/n-1cmPb.root
/run/beamOn 1000000