# Macro file for nDa
# 
# To be run preferably in batch, without graphics:
# % nDa[a,b] runFe.mac
#
/tracking/storeTrajectory 0
/run/numberOfThreads 24
/run/initialize
/control/execute gps_iso.mac
/gps/particle neutron

/gps/energy 5 MeV
#/nDa/det/setTargetRadius 2 cm
/analysis/setFileName Mov2sOutput/5n-D2.root
/run/beamOn 1000000

#/gps/energy 14 MeV
#/nDa/det/setTargetRadius 2 cm
#/analysis/setFileName Mov2sOutput/14n-D2.root
#/run/beamOn 1000000